import { NextRequest, NextResponse } from "next/server";
import { getJob } from "@/lib/store";

// English WebVTT for the result player's <track> — generated by the pipeline.
export async function GET(_req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const job = getJob(id);
  if (!job) return NextResponse.json({ error: `Unknown job: ${id}` }, { status: 404 });
  if (!job.subtitlesVtt) {
    return NextResponse.json({ error: `Job ${id} has no subtitles yet` }, { status: 404 });
  }
  return new NextResponse(job.subtitlesVtt, {
    headers: { "Content-Type": "text/vtt; charset=utf-8" },
  });
}
