/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiJobsRouteImport } from './routes/api/jobs'
import { Route as ApiJobsIdRouteImport } from './routes/api/jobs.$id'
import { Route as ApiJobsIdApproveRouteImport } from './routes/api/jobs.$id.approve'
import { Route as ApiJobsIdImageRouteImport } from './routes/api/jobs.$id.image'
import { Route as ApiJobsIdRecheckRouteImport } from './routes/api/jobs.$id.recheck'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsRoute = ApiJobsRouteImport.update({
  id: '/api/jobs',
  path: '/api/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIdRoute = ApiJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiJobsRoute,
} as any)
const ApiJobsIdApproveRoute = ApiJobsIdApproveRouteImport.update({
  id: '/approve',
  path: '/approve',
  getParentRoute: () => ApiJobsIdRoute,
} as any)
const ApiJobsIdImageRoute = ApiJobsIdImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => ApiJobsIdRoute,
} as any)
const ApiJobsIdRecheckRoute = ApiJobsIdRecheckRouteImport.update({
  id: '/recheck',
  path: '/recheck',
  getParentRoute: () => ApiJobsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/api/jobs/$id': typeof ApiJobsIdRouteWithChildren
  '/api/jobs/$id/approve': typeof ApiJobsIdApproveRoute
  '/api/jobs/$id/image': typeof ApiJobsIdImageRoute
  '/api/jobs/$id/recheck': typeof ApiJobsIdRecheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/api/jobs/$id': typeof ApiJobsIdRouteWithChildren
  '/api/jobs/$id/approve': typeof ApiJobsIdApproveRoute
  '/api/jobs/$id/image': typeof ApiJobsIdImageRoute
  '/api/jobs/$id/recheck': typeof ApiJobsIdRecheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/api/jobs/$id': typeof ApiJobsIdRouteWithChildren
  '/api/jobs/$id/approve': typeof ApiJobsIdApproveRoute
  '/api/jobs/$id/image': typeof ApiJobsIdImageRoute
  '/api/jobs/$id/recheck': typeof ApiJobsIdRecheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/jobs'
    | '/api/jobs/$id'
    | '/api/jobs/$id/approve'
    | '/api/jobs/$id/image'
    | '/api/jobs/$id/recheck'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/jobs'
    | '/api/jobs/$id'
    | '/api/jobs/$id/approve'
    | '/api/jobs/$id/image'
    | '/api/jobs/$id/recheck'
  id:
    | '__root__'
    | '/'
    | '/api/jobs'
    | '/api/jobs/$id'
    | '/api/jobs/$id/approve'
    | '/api/jobs/$id/image'
    | '/api/jobs/$id/recheck'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiJobsRoute: typeof ApiJobsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs': {
      id: '/api/jobs'
      path: '/api/jobs'
      fullPath: '/api/jobs'
      preLoaderRoute: typeof ApiJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$id': {
      id: '/api/jobs/$id'
      path: '/$id'
      fullPath: '/api/jobs/$id'
      preLoaderRoute: typeof ApiJobsIdRouteImport
      parentRoute: typeof ApiJobsRoute
    }
    '/api/jobs/$id/approve': {
      id: '/api/jobs/$id/approve'
      path: '/approve'
      fullPath: '/api/jobs/$id/approve'
      preLoaderRoute: typeof ApiJobsIdApproveRouteImport
      parentRoute: typeof ApiJobsIdRoute
    }
    '/api/jobs/$id/image': {
      id: '/api/jobs/$id/image'
      path: '/image'
      fullPath: '/api/jobs/$id/image'
      preLoaderRoute: typeof ApiJobsIdImageRouteImport
      parentRoute: typeof ApiJobsIdRoute
    }
    '/api/jobs/$id/recheck': {
      id: '/api/jobs/$id/recheck'
      path: '/recheck'
      fullPath: '/api/jobs/$id/recheck'
      preLoaderRoute: typeof ApiJobsIdRecheckRouteImport
      parentRoute: typeof ApiJobsIdRoute
    }
  }
}

interface ApiJobsIdRouteChildren {
  ApiJobsIdApproveRoute: typeof ApiJobsIdApproveRoute
  ApiJobsIdImageRoute: typeof ApiJobsIdImageRoute
  ApiJobsIdRecheckRoute: typeof ApiJobsIdRecheckRoute
}

const ApiJobsIdRouteChildren: ApiJobsIdRouteChildren = {
  ApiJobsIdApproveRoute: ApiJobsIdApproveRoute,
  ApiJobsIdImageRoute: ApiJobsIdImageRoute,
  ApiJobsIdRecheckRoute: ApiJobsIdRecheckRoute,
}

const ApiJobsIdRouteWithChildren = ApiJobsIdRoute._addFileChildren(
  ApiJobsIdRouteChildren,
)

interface ApiJobsRouteChildren {
  ApiJobsIdRoute: typeof ApiJobsIdRouteWithChildren
}

const ApiJobsRouteChildren: ApiJobsRouteChildren = {
  ApiJobsIdRoute: ApiJobsIdRouteWithChildren,
}

const ApiJobsRouteWithChildren =
  ApiJobsRoute._addFileChildren(ApiJobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiJobsRoute: ApiJobsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
